title: Junjie Ma
email: junjiema@seas.harvard.edu
description: >- # this means to ignore newlines until "baseurl:"
  A webpage for Junjie.
baseurl: "webpage" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

